[package]
name = "pactorio"
version = "0.2.2"
authors = ["figsoda"]
edition = "2018"
license = "MPL-2.0"
homepage = "https://github.com/figsoda/pactorio"
repository = "https://github.com/figsoda/pactorio"
readme = "README.md"
keywords = ["factorio"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.32"
serde_json = "1.0.57"
structopt = "0.3.17"
toml = "0.5.6"
walkdir = "2.3.1"

[dependencies.serde]
version = "1.0.115"
features = ["derive"]
