[package]
name = "pactorio"
version = "0.5.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2018"
description = "Pactorio is a tool that packages factorio mods and uses toml for config files. "
readme = "README.md"
homepage = "https://github.com/figsoda/pactorio"
repository = "https://github.com/figsoda/pactorio"
license = "MPL-2.0"
keywords = ["factorio", "package"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.38"
globset = "0.4.6"
multipart = { version = "0.17.1", default-features = false, features = ["client"] }
regex = "1.4.3"
rpassword = "5.0.1"
rprompt = "1.0.5"
select = "0.5.0"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.61"
serde_urlencoded = "0.7.0"
structopt = "0.3.21"
toml = "0.5.8"
ureq = { version = "2.0.1", features = ["json"] }
walkdir = "2.3.1"

[dependencies.zip]
version = "0.5.9"
default-features = false
features = ["bzip2", "deflate"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
