[package]
name = "pactorio"
version = "0.6.0"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = "Mod packager for Factorio"
readme = "README.md"
homepage = "https://github.com/figsoda/pactorio"
repository = "https://github.com/figsoda/pactorio"
license = "MPL-2.0"
keywords = ["factorio", "package"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.17", features = ["cargo", "derive", "unicode"] }
globset = "0.4.9"
is_executable = "1.0.1"
multipart = { version = "0.18.0", default-features = false, features = ["client"] }
rpassword = "7.1.0"
serde = { version = "1.0.146", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
toml = "0.5.9"
ureq = { version = "2.5.0", features = ["json"] }
walkdir = "2.3.2"
zstd = "*"

[dependencies.zip]
version = "0.6.3"
default-features = false
features = ["bzip2", "deflate", "zstd"]

[build-dependencies]
clap = { version = "4.0.17", features = ["derive"] }
clap_complete = "4.0.3"
clap_mangen = "0.2.3"

[build-dependencies.zip]
version = "0.6.3"
default-features = false
features = ["bzip2", "deflate", "zstd"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
