cargo-features = ["strip"]

[package]
name = "pactorio"
version = "0.4.8"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2018"
description = "Pactorio is a tool that packages factorio mods and uses toml for config files. "
readme = "README.md"
homepage = "https://github.com/figsoda/pactorio"
repository = "https://github.com/figsoda/pactorio"
license = "MPL-2.0"
keywords = ["factorio", "package"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.34"
globset = "0.4.6"
multipart = { version = "0.17.0", default-features = false, features = ["client"] }
regex = "1.4.2"
rpassword = "5.0.0"
rprompt = "1.0.5"
select = "0.5.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
serde_urlencoded = "0.7.0"
structopt = "0.3.20"
toml = "0.5.7"
ureq = { version = "1.5.2", features = ["json"] }
walkdir = "2.3.1"

[dependencies.zip]
version = "0.5.8"
default-features = false
features = ["bzip2", "deflate"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
strip = "symbols"
