cargo-features = ["strip"]

[package]
name = "pactorio"
version = "0.4.5"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2018"
license = "MPL-2.0"
description = "Pactorio is a tool that packages factorio mods and uses toml for config files. "
homepage = "https://github.com/figsoda/pactorio"
repository = "https://github.com/figsoda/pactorio"
readme = "README.md"
keywords = ["factorio", "package"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.33"
globset = "0.4.5"
regex = "1.4.1"
rpassword = "5.0.0"
rprompt = "1.0.5"
select = "0.5.0"
tokio = { version = "0.2.22", features = ["macros"] }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.59"
structopt = "0.3.20"
toml = "0.5.7"
walkdir = "2.3.1"
zip = { version = "0.5.8", default_features = false }

[dependencies.reqwest]
version = "0.10.8"
default_features = false
features = ["cookies", "json", "rustls-tls"]

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
