[package]
name = "pactorio"
version = "0.1.0"
authors = ["figsoda"]
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.6"
serde_json = "1.0.41"
toml = "0.5.4"
walkdir = "2.2.9"

[dependencies.serde]
version = "1.0.102"
features = ["derive"]
