[package]
name = "pactorio"
version = "0.5.2"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = "Mod packager for Factorio"
readme = "README.md"
homepage = "https://github.com/figsoda/pactorio"
repository = "https://github.com/figsoda/pactorio"
license = "MPL-2.0"
keywords = ["factorio", "package"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.8", features = ["cargo", "derive", "unicode"] }
globset = "0.4.8"
is_executable = "1.0.1"
multipart = { version = "0.18.0", default-features = false, features = ["client"] }
regex = "1.5.5"
rpassword = "5.0.1"
rprompt = "1.0.5"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.79"
serde_urlencoded = "0.7.1"
toml = "0.5.8"
ureq = { version = "2.4.0", features = ["cookies", "json"] }
walkdir = "2.3.2"

[dependencies.zip]
version = "0.5.13"
default-features = false
features = ["bzip2", "deflate"]

[build-dependencies]
clap = { version = "3.1.8", features = ["derive"] }
clap_complete = "3.0.4"

[build-dependencies.zip]
version = "0.5.13"
default-features = false
features = ["bzip2", "deflate"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
