[package]
name = "pactorio"
version = "0.2.1"
authors = ["figsoda"]
edition = "2018"

[dependencies]
failure = "0.1.8"
serde_json = "1.0.57"
structopt = "0.3.16"
toml = "0.5.6"
walkdir = "2.3.1"

[dependencies.serde]
version = "1.0.115"
features = ["derive"]
