cargo-features = ["strip"]

[package]
name = "pactorio"
version = "0.4.3"
authors = ["figsoda"]
edition = "2018"
license = "MPL-2.0"
description = "Pactorio is a tool that packages factorio mods and uses toml for config files. "
homepage = "https://github.com/figsoda/pactorio"
repository = "https://github.com/figsoda/pactorio"
readme = "README.md"
keywords = ["factorio"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.32"
globset = "0.4.5"
regex = "1.3.9"
rpassword = "5.0.0"
rprompt = "1.0.5"
select = "0.5.0"
tokio = { version = "0.2.22", features = ["macros"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
structopt = "0.3.17"
toml = "0.5.6"
walkdir = "2.3.1"
zip = { version = "0.5.8", default_features = false }

[dependencies.reqwest]
version = "0.10.8"
default_features = false
features = ["cookies", "json", "rustls-tls"]

[profile.release]
strip = "symbols"
