name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  create_release:
    name: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: "[Changelog](https://github.com/figsoda/pactorio/blob/main/CHANGELOG.md)"

  release:
    name: release
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            ext: .exe
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            ext: .exe
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            use-cross: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          default: true

      - name: Cargo build
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target ${{ matrix.target }}
        env:
          RUSTFLAGS: -Z strip=symbols

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          tag: ${{ github.ref }}
          file: target/${{ matrix.target }}/release/pactorio${{ matrix.ext }}
          asset_name: pactorio-${{ matrix.target }}${{ matrix.ext }}

  completions:
    name: completions
    needs: create_release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - name: Cargo build
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
        env:
          GEN_COMPLETIONS: 1

      - name: Find generated completions
        run: |
          outputs=(target/debug/build/pactorio-*/out/completions)
          cp -r "${outputs[0]}" completions

      - name: Upload bash completion
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          tag: ${{ github.ref }}
          file: ./completions/pactorio.bash

      - name: Upload elvish completion
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          tag: ${{ github.ref }}
          file: ./completions/pactorio.elv

      - name: Upload fish completion
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          tag: ${{ github.ref }}
          file: ./completions/pactorio.fish

      - name: Upload powershell completion
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          tag: ${{ github.ref }}
          file: ./completions/_pactorio.ps1
          asset_name: pactorio.ps1

      - name: Upload zsh completion
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          tag: ${{ github.ref }}
          file: ./completions/_pactorio
          asset_name: pactorio.zsh
